portofolio/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'portofolio'

urlpatterns = [
    path('', views.launch, name='launch'),
    path('about/', views.about, name='about'),
    path('skills/', views.skills, name='skills'),
    path('experiences/', views.experiences, name='experiences'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('schedules/', views.show_jadwal, name='show_jadwal'),
    path('schedules/add/', views.add_jadwal, name='add_jadwal'),

    url(r'schedules/(?P<pk>[0-9]+)/delete/$', views.JadwalDelete.as_view(), name='delete_jadwal'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portofolio.urls')),
]

portofolio/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Jadwal(models.Model):
    tanggal = models.DateTimeField()
    nama_Kegiatan = models.CharField(max_length=100)
    tempat = models.CharField(max_length=50)
    kategori = models.CharField(max_length=50)

    def __str__(self):
        return self.nama_Kegiatan

    def getTanggal(self):
        return self.tanggal.strftime("%d")
    
    def getBulan(self):
        return self.tanggal.strftime("%b")

    def getHari(self):
        return ' ' + self.tanggal.strftime("%A")

    def getJam(self):
        return ' ' + self.tanggal.strftime("%H:%M:%S")

    def getTempat(self):
        return ' ' + self.tempat
    

portofolio/forms.py
from django import forms

from .models import Jadwal


class JadwalForm(forms.ModelForm):

    class Meta:
        model = Jadwal
        fields = ['tanggal', 'nama_Kegiatan', 'tempat', 'kategori']
        widgets = {
            'tanggal': forms.DateTimeInput(attrs={'class': 'datetime-input'})
        }
        

portofolio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Jadwal
from .forms import JadwalForm
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

# Create your views here.
def index(request):
    return render(request, 'index.html')

def launch(request):
    return render(request, 'launch.html')

def about(request):
    return render(request, 'about.html')

def skills(request):
    return render(request, 'skills.html')

def experiences(request):
    return render(request, 'experiences.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

def show_jadwal(request):
    semua_jadwal = Jadwal.objects.order_by('tanggal')
    return render(request, 'show_jadwal.html', {'semua_jadwal' : semua_jadwal})

def add_jadwal(request):
    if request.method == "POST":
        form = JadwalForm(request.POST)
        if form.is_valid():
            jadwal = form.save()
            jadwal.save()        
            return redirect('/schedules/')
    else:
        form = JadwalForm()
        
    return render(request, 'add_jadwal.html', {'form': form})

# def delete_jadwal(request, pk):
#     template = 'delete_jadwal.html'
#     kegiatan = get_object_or_404(Jadwal, pk=pk)

#     try:
#         if request.method == 'POST':
#             form = JadwalForm(request.POST, instance=kegiatan)
#             kegiatan.delete()
#             messages.success(request, 'Kegiatan berhasil dihapus')
#         else:
#             form = JadwalForm(instance=kegiatan)
#     context = {
#         'form':form,
#     }
#     return render(request, template, context)

class JadwalDelete(DeleteView):
    model = Jadwal
    success_url = reverse_lazy('portofolio:show_jadwal')

portofolio/templates/about.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
		<!-- ABOUT PAGE -->
		<div class="about-page" id="ap">
			<h2>Tentang</h2>

			<p class="tentang-saya">
			 	Rifqi adalah mahasiswa Ilmu Komputer di Fasilkom UI. <br>
				Di tahun kedua perkuliahannya, pemuda yang aktif, energik, dan ceria ini <br>
				sangat senang mempelajari mata perancangan pemrograman web.
			</p>

			<h2>Pendidikan</h2>

			<div class="pendidikan-saya">
				<div class="instansi">
					<img src="{% static 'images/edu/logo_sma6.png' %}" class="logo-instansi">
					<h4>SMA Negeri 6 Bogor</h4>
				</div>

				<div class="instansi">
					<img src="{% static 'images/edu/logo_ui.png' %}" class="logo-instansi">
					<h4>Universitas Indonesia</h4>
				</div>	
			</div>

		</div>
	{% endblock %}

portofolio/templates/add_jadwal.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

	

	<h3 class="h3_tambah">Tambah Kegiatan Baru</h3>
    <form method="POST" class="post-form form-group">{% csrf_token %}
    	<div class="bgform">
        	{{ form.as_p }}
        </div>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    <script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
	</script>

	{% endblock %}

portofolio/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Story-5 Rifqi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

</head>



	<nav class="navbar navbar-expand-lg warnaNavbar navbar-expand" id="nb">

  		<a class="navbar-brand" href="{% url 'portofolio:launch' %}">Portofolio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      		<a class="nav-item nav-link" href="{% url 'portofolio:about' %}">Tentang</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:skills' %}">Kemampuan</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:experiences' %}">Pengalaman</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:gallery' %}">Galeri</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:show_jadwal' %}">Jadwal</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:contact' %}">Hubungi</a>
	    	</div>
  		</div>
	</nav>

<body>
	{% block content %}
            

    {% endblock %}
</body>

portofolio/templates/contact.html
{% extends 'base.html' %}
{% load static %}


	{% block content %}
	<!-- CONTACT PAGE -->
		<div class="hubungi-saya" id="cp">
			<h3>Hubungi Saya</h3>
			<div class="contact-container">
				<a href="mailto:mqnisen@gmail.com" target="_blank"><img src="{% static 'images/contact/logo_email.png' %}" class="logo-cp"/></a>
				<a href="https://www.linkedin.com/in/mrifqi" target="_blank"><img src="{% static 'images/contact/logo_linkedin.png' %}" class="logo-cp"/></a>
				<a href="http://line.me/ti/p/mqnisen" target="_blank"><img src="{% static 'images/contact/logo_line.png' %}" class="logo-cp"/></a>
				<a href="https://www.instagram.com/enbeqi" target="_blank"><img src="{% static 'images/contact/logo_ig.png' %}" class="logo-cp"/></a>
			</div>
			<a href="{% url 'portofolio:launch' %}"><img src="{% static 'images/iconfinder_upbutton.png' %}" class="scroll-btn"/></a>
		</div>
		
	{% endblock %}

portofolio/templates/delete_jadwal.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

	

	<h3 class="h3_tambah">Tambah Kegiatan Baru</h3>
    <form method="POST" class="post-form form-group">{% csrf_token %}
    	<div class="bgform">
        	{{ form.as_p }}
        </div>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
    <script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
	</script>

	{% endblock %}

portofolio/templates/experiences.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
		<!-- EXPERIENCES PAGE -->
		<div class="pengalaman-saya" id="exp">
			<h3>Organisasi</h3>
			<div class="exp-box">
				<img src="{% static 'images/exp/logo_bem.png' %}" class=logo-exp>
				<div class="exp-text">
					<h5>BEM FASILKOM UI 2019</h5>
					<h6>Dept. Akademis dan Kepemimpinan</h6>
				</div>
			</div>

			<h3 class="vol-header">Kepanitiaan</h3>
			<div class="vol-container">
				<div class="exp-box">
					<img src="{% static 'images/exp/logo_cf.png' %}" class=logo-exp>
					<div class="exp-text">
						<h5>COMPFEST 11</h5>
						<h6>Staff Playground</h6>
					</div>
				</div>

				<div class="exp-box">
					<img src="{% static 'images/exp/logo_cgt.png' %}" class=logo-exp>
					<div class="exp-text">
						<h5>Computers Get Together</h5>
						<h6>Staff Bazaar dan Konsumsi</h6>
					</div>
				</div>

				<div class="exp-box">
					<img src="{% static 'images/exp/logo_siwak.png' %}" class=logo-exp>
					<div class="exp-text">
						<h5>SIWAK-NG</h5>
						<h6>Staff Akomodasi</h6>
					</div>
				</div>

			</div>
		</div>
	{% endblock %}

portofolio/templates/gallery.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
		<!-- GALLERY PAGE -->
		<div class="galeri-saya" id="gs">
			
			<div class="photos-container">
				<div class="right-container">
					<img src="{% static 'images/gallery/gf1-1.jpg' %}">
					<img src="{% static 'images/gallery/gf1-2.jpg' %}">
					<img src="{% static 'images/gallery/gf1-3.jpg' %}">
					<img src="{% static 'images/gallery/gf1-4.jpg' %}">
				</div>
				<div class="left-container">
					<img src="{% static 'images/gallery/gf2-1.jpg' %}">
					<img src="{% static 'images/gallery/gf2-2.jpg' %}">
					<img src="{% static 'images/gallery/gf2-3.jpg' %}">
					<img src="{% static 'images/gallery/gf2-4.jpg' %}">
				</div>
				<div class="right-container">
					<img src="{% static 'images/gallery/gf3-1.jpg' %}">
					<img src="{% static 'images/gallery/gf3-2.jpg' %}">
					<img src="{% static 'images/gallery/gf3-3.jpg' %}">
					<img src="{% static 'images/gallery/gf3-4.jpg' %}">
				</div>
			</div>
		</div>
		
	{% endblock %}

portofolio/templates/launch.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}

		<!-- LAUNCH PAGE -->
		<div class="launch-page" id="lp">
			<img src="{% static 'images/profile/foto-b.png' %}" class="foto-saya">
			<p>Muhammad Rifqi</p>
			<a href="{% url 'portofolio:about' %}"><img src="{% static 'images/iconfinder_downbutton.png' %}" class="scroll-btn"/></a>

		</div>

	{% endblock %}

portofolio/templates/show_jadwal.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}

		{% for jadwal in semua_jadwal %}
		<!-- SHOW JADWAL PAGE -->

		<div class="row row-striped">
			<div class="col-2 text-right">
				<h1 class="display-4"><span class="badge badge-secondary">{{ jadwal.getTanggal }}</span></h1>
				<h2>{{ jadwal.getBulan }}</h2>
			</div>
			<div class="col-10">
				<h3 class="text-uppercase"><strong>{{ jadwal.nama_Kegiatan }}</strong></h3>
				<ul class="list-inline">
				    <li class="list-inline-item"><i class="fa fa-calendar" style="color:#000000AA;" aria-hidden="true"></i>{{ jadwal.getHari }}</li>
				    <!--jadwal.tanggal.strftime("%A")-->
					<li class="list-inline-item"><i class="fa fa-clock-o" style="color:#000000AA;" aria-hidden="true"></i> {{ jadwal.getJam }}</li>
					<li class="list-inline-item"><i class="fa fa-location-arrow" style="color:#000000AA;" aria-hidden="true"></i>{{ jadwal.getTempat }}</li>
				</ul>
				<p>Kategori: {{ jadwal.kategori }}</p>
			</div>
			
			<div class="del-jadwal col-12">
				<form action="{% url 'portofolio:delete_jadwal' jadwal.id %}" method="post">
					{% csrf_token %}
					<input type="hidden" name="jadwal_id" value="{{ jadwal.id }}"/>
					<button type="" class="btn-sm btn-danger" style="margin-left: 10%">
						Hapus
					</button> 
				</form>	
			</div>
			
		</div>


		{% endfor %}

		
			<div class="col text-center">
  				<a class="btn" href="{% url 'portofolio:add_jadwal' %}">Tambah Kegiatan</a>
			</div>
		

	{% endblock %}

portofolio/templates/skills.html
{% extends 'base.html' %}
{% load static %}

	{% block content %}
<!-- SKILLS PAGE -->
		<div class="kemampuan-saya" id="skl">
			<h2>Kemampuan</h2>

			<div class="skill-container">
				<div class="skill">
					<h5 class="name">python</h5>
					<img src="{% static 'images/skills/logo_python.png' %}" class=logo-skill>
					<h5>7/10</h5>
				</div>

				<div class="skill">
					<h5 class="name">java</h5>
					<img src="{% static 'images/skills/logo_java.png' %}" class=logo-skill>
					<h5>8/10</h5>
				</div>

				<div class="skill">
					<h5 class="name">html-css</h5>
					<img src="{% static 'images/skills/logo_html-css.png' %}" class=logo-skill>
					<h5>7/10</h5>
				</div>
			</div>
		</div>

	{% endblock %}